@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jul 25 13:03:50 +0300 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim posit_mult_8bit_tb_v_func_impl -key {Post-Implementation:sim_1:Functional:posit_mult_8bit_tb_v} -tclbatch posit_mult_8bit_tb_v.tcl -view C:/project_posit_mult_dsp/posit_mult_behav.wcfg -log simulate.log"
call xsim  posit_mult_8bit_tb_v_func_impl -key {Post-Implementation:sim_1:Functional:posit_mult_8bit_tb_v} -tclbatch posit_mult_8bit_tb_v.tcl -view C:/project_posit_mult_dsp/posit_mult_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
